### ISSUE TITLE
Ghost match (a Riot API bug)

### ISSUE THREAD

**Issue by simoncos** [meraki-analytics/cassiopeia#57] opened 2016-02-23 11:32 UTC
Hey guys,

I spent half an hour to understand an error happened when I used Cass. Firstly you can try this query, and will find a match_id `'2405929288'`:

`https://na.api.pvp.net/api/lol/na/v2.2/matchlist/by-summoner/73099728?rankedQueues=RANKED_SOLO_5x5&seasons=PRESEASON2016&api_key=XXX
`

Then you try to get the details of this match, and it will return 404, which means even if we can find a match_id in one match list, we are not 100% sure it has record from the `match` method:

`https://na.api.pvp.net/api/lol/na/v2.2/match/2405929288?includeTimeline=0&api_key=XXX
`

```
{
	"status": {
		"message": "Not Found",
		"status_code": 404
	}
}
```
Because of this, we may get an `None ` when we use `match = riotapi.get_match(mf)`
in Cass. Right now I choose to use `if match is None` to avoid this (can not use '==' because Match.\_\_eq\_\_ use Match.id). 

**Update**: And then I found the region of this match is 'EUW', which means the region setting is useless?

**Update 2**: I reconsidered this problem, and found that if Cass. returned 404 correctly, there should not be this problem. So I think the exception part of Cass. should be checked.

**Comment by jjmaldonis** [comment] 2016-02-23 17:00
Using `if match is None` is the correct way to test if the match was pulled successfully. We deliberately do not support `if match == None` because python is moving away from supporting this entirely, the `is` keyword is more correct for cases like this.

Doing things like `if ___ is None` can be done throughout Cassiopeia for various objects/attributes, including `match.participants[0].stats.node_capture_assists` as another example that accesses a specific attribute of a match rather than the entire match itself. Riot may not return data for every object/attribute, so we set any unreturned values to None.

>And then I found the region of this match is 'EUW', which means the region setting is useless?

If you are making the call `https://na.api.pvp.net/api/lol/na/v2.2/match/2405929288?includeTimeline=0&api_key=XXX` and it is returning an `euw` match, there is nothing we can do about that. The correct call to `na` is being made, Riot is just returning what may be the wrong match. Without seeing more of your output and code I cannot be sure.

>I reconsidered this problem, and found that if Cass. returned 404 correctly, there should not be this problem. So I think the exception part of Cass. should be checked.

Yes, 404s are handled in Cass by setting the object that is returned to `None`. This is intended. Are you proposing to raise an exception on a 404 instead?

**Comment by WxWatch** [comment] 2016-02-23 17:09
> And then I found the region of this match is 'EUW', which means the region setting is useless?

It sounds like this is a current limitation of Cass. When a summoner changes regions, their match history stays with them (e.g. I move my NA account to EUW, then my NA matches will still remain in my match history from the API). Since Cass is relying on a region parameter set by the user, then it isn't taking this into account.

You could /probably/ get around this by temporarily changing the region to the match's region, then changing it back (depends on how your processes are setup). 

I believe support for this is being planned for the next version, but I'm not certain of an ETA or anything on that.

**Comment by simoncos** [comment] 2016-02-23 17:55
@jjmaldonis Sorry I hadn't read the exception handling codes in Cass when I posted the issue. In my view, raising a `404` exception may be better because it will be consistent with API and thus I can handle all kinds of exceptions from API in one decorator like `https://github.com/meraki-analytics/cassiopeia/blob/master/example/match_collection.py` and do not need to consider other situations.

And thanks for both of you for explaining why this may happen. I'm from China and didn't know summoners can change between some regions. @WxWatch

**Comment by robrua** [comment] 2016-02-23 18:03
Ok, I'm seriously confused right now by this entire discussion right now. Cass **shouldn't** be returning `None` from `riotapi.get_match` if the match doesn't exist, and **should** be raising an `APIError` for the 404 it received from Riot.

This is the behavior I expect from cass right now, and the behavior I see when testing on my own machine. Can someone give me steps or code to reproduce the `None` response you guys are talking about?

On a side not, we should probably make `riotapi.get_matches()` swallow the 404 and return None, as it's a waste to ignore all the other matches you were asking for that didn't get a 404.

**Comment by simoncos** [comment] 2016-02-23 18:28
Sorry, my fault. Cass raises APIError correctly:

`
APIError: Server returned error 404 on call: https://na.api.pvp.net/api/lol/na/v2.2/match/2405929288?includeTimeline=True&api_key=04c9abf6-0c85-406c-8520-3d86684e9cb1
`
And it seems the problem was actually made by the decorator I use.

```
def auto_retry(api_call_method):
    """ A decorator to automatically retry 500s (Service Unavailable) and skip 400s (Bad Request) or 404 (Not Found). """
    def call_wrapper(*args, **kwargs):
        try:
            return api_call_method(*args, **kwargs)
        except APIError as error:
            # Try Again Once
            if error.error_code in [500, 503]:
                try:
                    print("Got a 500 or 503, trying again...")
                    time.sleep(5) #simoncos
                    return api_call_method(*args, **kwargs)
                except APIError as another_error:
                    if another_error.error_code in [500, 503, 400, 404]:
                        pass
                    else:
                        # Fatal also? simoncos
                        raise another_error

            # Skip
            elif error.error_code in [400, 404]:
                print("Got a 400 or 404")
                pass #may make match None!!!

            # Fatal
            else:
                raise error
    return call_wrapper
```

Because of this,

**Comment by simoncos** [comment] 2016-02-23 18:34
And I agree that `riotapi.get_matches()` should not raise 404.

**Comment by robrua** [comment] 2016-02-23 18:39
Cool. Let us know if you run into any other problems.

As far as the more intelligent region handling, it will be in the next big update (a rewrite of Cass) which should be coming in the next month or so.

**Closed by robrua** 2016-02-23 18:39 UTC

**Comment by simoncos** [comment] 2016-02-23 18:42
Brilliant.

**Comment by jjmaldonis** [comment] 2016-02-23 19:27
@simoncos Gotcha, you are using the `auto_retry` decorator in `match_collection.py`. That's a good catch that 404s return None, because no return statement is ever hti. I wrote that decorator and maybe it should be revised. I'll try to think about it tonight, but if you have any suggestions on how to improve that decorator when it comes to error handling that makes the decorator more robust, feel free to let us know and we can update it.

**Comment by simoncos** [comment] 2016-02-25 14:38
@jjmaldonis I think the key point is not the decorator, which is pretty nice as far as I see, but how region switching influences the consistency between `matchlist` and `match` methods (we input the some `region` parameter value to both methods, but as you know, `matchlist` in the current edition returns all records of a summoner only if it has been in that region, while `match` only returns those exactly from the given region). 

I guess the best that Cass can do may be a more intelligient region handling, just as Rob mentioned.
