### ISSUE TITLE
(Multithread) Generator already executing

### ISSUE THREAD

**Issue by xEcEz** [meraki-analytics/cassiopeia#231] opened 2018-05-04 15:27 UTC
When used in a multithreaded environment, the leagues endpoint sometimes throws this error:

```python
    leagueInfo = summoner.leagues[Queue.ranked_solo_fives]
  File "cassiopeia/core/summoner.py", line 211, in leagues
    ids = {position.league_id for position in positions}
  File "cassiopeia/core/summoner.py", line 211, in <setcomp>
    ids = {position.league_id for position in positions}
  File "/usr/local/lib/python3.6/dist-packages/merakicommons/container.py", line 354, in __iter__
    yield next(self)
  File "/usr/local/lib/python3.6/dist-packages/merakicommons/container.py", line 365, in __next__
    value = next(self._generator)
ValueError: generator already executing
```

**Comment by jjmaldonis** [comment] 2018-05-04 16:05
Do you have some code to reproduce the issue?

**Comment by xEcEz** [comment] 2018-05-04 16:29
```python
from multiprocessing.dummy import Pool as ThreadPool
import itertools
from cassiopeia import Summoner

def useLeaguesEndpoint(i, summoner):
    leagues = summoner.leagues

summoner = Summoner(name='Grig1', region='NA')
pool = ThreadPool(16)
pool.starmap(useLeaguesEndpoint, zip(range(1, 1000), itertools.repeat(summoner)))
pool.close()
pool.join()
```

**Comment by jjmaldonis** [comment] 2018-05-04 17:08
This is an interesting issue and seems to be an inherent part of python. It's going to take some thinking to figure out how to handle this one.

That said, the reason this error is occurring is because there are duplicate summoners in the list passed to `pool.starmap`. If you remove the duplicates first, the code won't error.

Mostly for myself, here is some code that reproduces the same error in pure python (not using Cass):

```
from multiprocessing.dummy import Pool as ThreadPool

def count():
    i = 0
    while True:
        i += 1
        yield i
c = count()

def load(c):
    return {c.__next__() for _ in range(10000)}

pool = ThreadPool(16)
pool.map(load, [c for _ in range(100)])
pool.close()
pool.join()
```

Note that if you replace `c` with `count()` in the `pool.map` function that the code runs without erroring. This is because a different generator is being passed to `load` within each of the threads.

**Comment by xEcEz** [comment] 2018-05-04 17:53
Yes, I looked online before posting here and found [that explanation](https://anandology.com/blog/using-iterators-and-generators/), which provide a similar example to yours. It seems like the solution would be to switch to iterators and protect them with locks.

In my use case, I did not realize until you provided this answer that summoner.leagues could be called at the same time on the same summoner. I could rewrite this part of my code to avoid doing such a thing so thanks!

**Comment by jjmaldonis** [comment] 2018-10-16 19:13
Since this is such a specific use-case and you found a workaround for your code, I'm going to close this issue without fixing it. If someone runs across this same problem and finds this thread, please re-open the issue and let us know what's going on.

**Closed by jjmaldonis** 2018-10-16 19:13 UTC
