### ISSUE TITLE
Participant from match_history : how to skip one of them ?

### ISSUE THREAD

**Issue by DangTaemi** [meraki-analytics/cassiopeia#318] opened 2020-04-16 11:28 UTC
Hello,

I am new to python and API. I would like to get info on each participant in a player's match history.
However, one of these participants doesn't exist anymore. The ID is "0" and it returns a bad request.
I tried to raise an exception, to skip the player if encountered but... It doesn't work.

Player that I want to skip is named Renekton in match n°2 (3rd)

```
player = Summoner(name="Laina", region="EUW")
o = 0
    
if joueur.exists == False :
   break
else :
   try :
        for match in joueur.match_history:
            if o == 4 :
                print("End of", o, "matchs \n")
                break
            else :
                print("Beginning of match n°", o)
                for participant in match.participants: 
                    if participant.summoner.exists != False or participant.summoner.name != "Renekton" or participant.summoner.account_id != 0 :
                        print("Match", o, ":", participant.summoner.name)
                        try :
                            matchs_infos = matchs_infos.append({
                                        'ID match' : match.id,
                                        'Date match' : match.creation, 
                                        'Season' : match.season.value,
                                        'Game mode' : match.queue.value,
                                        'Solo / Custom' : match.type.value,
                                        'Participant ID' : participant.summoner.id, 
                                        'Participant name' : participant.summoner.name,
                                        'Participant rank' : participant.summoner.league_entries.fives.tier,
                                        'Team side' : participant.team.side,
                                        'Champion' : participant.champion.name, 
                                        'Role' : participant.role, 
                                        'Lane' : participant.lane, 
                                        'Win' : participant.stats.win,
                                        'Player study' : int(0)
                            }, ignore_index = True)
                        except :
                            continue
                    
                        if participant.summoner.id == player.id or participant.summoner.name == player.name :
                            matchs_infos.loc[np.logical_and(matchs_infos['Participant ID'] == player.id, matchs_infos['ID match'] == match.id),'Player study']=int(1)
                        else : 
                            pass
                        
                    else :
                        continue
                print("End of match n°", o, "\n")
                o = o + 1
```

Also, why is rank_last_season not working ? Patch.season also has an error...

Thank you.

**Comment by jjmaldonis** [comment] 2020-04-16 13:43
I'm pretty sure ID 0 means the player is a bot. Try this if statement:

`if participant.summoner.exists and not participant.is_bot:`

**Comment by DangTaemi** [comment] 2020-04-17 12:23
> I'm pretty sure ID 0 means the player is a bot. Try this if statement:
> 
> `if participant.summoner.exists and not participant.is_bot:`

I succeed by removing "summoner.exists" because it couldn't find the summoner.
However, I have another problem where an account id is used as a summoner id inside participants.summoner.name

It returns "NotFoundError: No source returned a query result!" ...

**Comment by jjmaldonis** [comment] 2020-04-17 18:22
Good call, and in fact you should be able to switch the order of the conditions so that you can leave `summoner.exists` in the if statement:  `if not participant.is_bot and participant.summoner.exists:`

Can you post your code that is causing the account id vs summer id issue? That doesn't sound like anything I've seen before. If we can reproduce it, we can track it down.

**Comment by DangTaemi** [comment] 2020-04-17 23:10
It blocked at the last print of this extract : 

```
player = Summoner(name=VioletFairy, region="EUW")
o = 0    
tot = len(player.match_history)
for match in player.match_history:
        if o == 100 :
            break
        else:
            for participant in match.participants: 
                if participant.summoner.account_id != "0" or not participant.is_bot and participant.summoner.exists :
                    try :
                        print("Match", o, ":", participant.summoner.name)
```
Returning this as a result : 
```
Making call: https://euw1.api.riotgames.com/lol/match/v4/matchlists/by-account/IsPMQsN0yTxI13wE4WgcwScNAebu5v_7MU4R5QsC7dB0CA?beginIndex=0&endIndex=100
Making call: https://ru.api.riotgames.com/lol/summoner/v4/summoners/by-account/IsPMQsN0yTxI13wE4WgcwScNAebu5v_7MU4R5QsC7dB0CA
Making call: https://ru.api.riotgames.com/lol/summoner/v4/summoners/by-account/IsPMQsN0yTxI13wE4WgcwScNAebu5v_7MU4R5QsC7dB0CA
NotFoundError: No source returned a query result!
```

When checking why this participant passed my conditions : 

`print(Summoner(id="IsPMQsN0yTxI13wE4WgcwScNAebu5v_7MU4R5QsC7dB0CA", region = "EUW").level)`

It returned me "AttributeError: 'SummonerData' object has no attribute 'level'"
KeyError400

However when I tried this instead : 
`print(Summoner(account_id="IsPMQsN0yTxI13wE4WgcwScNAebu5v_7MU4R5QsC7dB0CA", region = "EUW").level)`

It returned "180".

**Comment by jjmaldonis** [comment] 2020-04-18 02:13
Ahh, the summoner has changed regions. The first match in their match history is in Russia, not EUW, and the summoners generated from the participants inherit the match's region which is Russia in this case. The summoner no longer exists in Russia, however, so an error gets thrown.

This is an odd behavior that happens because the match history endpoint returns games for a summoner in all regions, but the match endpoint doesn't return the globally unique id associated with the summoners in the match (ie the puuid). Until Riot changes the behavior of these endpoints to use the puuid, there's nothing we can do there.

The only thing you can do is check the region of the matches that are being pulled, and handle different regions however you want.

**Comment by DangTaemi** [comment] 2020-05-01 15:19
Hello,
I managed to pass the error thanks to your answers.
I am now having another issue with Queue :

```
---------------------------------------------------------------------------
[...]

AttributeError: 'Match' object has no attribute '_lazy__queue'

During handling of the above exception, another exception occurred:

[...]

D:\Anaconda\lib\site-packages\cassiopeia\core\match.py in queue(self)
   1568     @lazy
   1569     def queue(self) -> Queue:
-> 1570         return Queue.from_id(self._data[MatchData].queue)
   1571 
   1572     @CassiopeiaGhost.property(MatchData)

D:\Anaconda\lib\site-packages\cassiopeia\data.py in from_id(id)
    555 
    556     def from_id(id: int):
--> 557         return {i: season for season, i in QUEUE_IDS.items()}[id]
    558 
    559     @property

KeyError: 2020
```

What is it due to ?

**Comment by jjmaldonis** [comment] 2020-05-01 16:22
Thanks for the report. Riot added some new queues it looks like recently and we had to update Cass. You can pull the new version using pip (or from github). Sometimes it takes a few minutes to get the newest version. You're looking for version 4.0.11.

I'm going to close this issue because this should be fixed now. Feel free to reopen if you are still having trouble with the queues.

**Closed by jjmaldonis** 2020-05-01 16:22 UTC
