### ISSUE TITLE
Support new /lol/league/v4/entries/{queue}/{tier}/{division} endpoint

### ISSUE THREAD

**Issue by Satrium** [meraki-analytics/cassiopeia#284] opened 2019-05-12 20:03 UTC
Riot games recently added a new endpoint, to paginate over all ranked summoners. This functionality should be supported in cassiopeia as well. (Link: https://developer.riotgames.com/api-methods/#league-v4/GET_getLeagueEntries)
I would try to implement it, and open a PR, but I'm not sure on how this functionality should be implemented.

**Comment by rlrs** [comment] 2019-05-15 11:32
I need this functionality, and I wouldn't mind implementing it, but I too am unfamiliar with the Cassiopeia codebase. It seems like all that needs to be implemented is perhaps a class in cassiopeia/core/league.py and a get_league function in cassiopeia/cassiopeia.py. Does this seem right?

**Comment by jjmaldonis** [comment] 2019-05-15 15:04
I did quite a bit of work on this a few days ago but I'm on the road right now. If you want to work on this go for it, but I hope I'll have it done in a few days. It probably needs a Dto class in cass/dto/league.py, a data and a core class in cass/core/league.py, and a get_league function in cass/cass.py (like you said). We also need a new function in cass/datastores/riotapi/league.py. That last file needs a lot of cleanup since Riot has been changing the league endpoints so much, so that's what's taking so long to fix up.

**Comment by jjmaldonis** [comment] 2019-05-15 23:03
Alright I got a bit done on this. It's not finished, and barely tested, but the basic functionality seems to work. We still need support for the cache and the kernel datastore (which is nearly a duplicate of the riotapi datastore so if someone has time to update the kernel/leagues.py file that would be great).

See this commit for more info: becf9b0e4703b40d0cf1e279eeb7777c421b7f48

**Comment by jjmaldonis** [comment] 2019-08-07 17:07
This should be done now.

**Closed by jjmaldonis** 2019-08-07 17:07 UTC
