### ISSUE TITLE
Getting summoner names with non-ASCII characters fails

### ISSUE THREAD

**Issue by blimmo** [meraki-analytics/cassiopeia#341] opened 2020-09-06 13:40 UTC
```python
import os

import cassiopeia as cass

cass.set_riot_api_key(os.getenv("RIOT_API_KEY"))

s = cass.get_summoner(name="é", region="EUW")
s.exists
```

Outputs `Making call: https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/\xc3\xa9`

Then fails with `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 65: ordinal not in range(128)`

I believe that the problem is [this line](https://github.com/meraki-analytics/cassiopeia/blob/d1a37a9783e4d65a2460fcad742cabd3e03e26d3/cassiopeia/datastores/riotapi/summoner.py#L38): `url = "https://{platform}.api.riotgames.com/lol/summoner/v4/summoners/by-name/{name}".format(platform=query["platform"].value.lower(), name=query["name"].replace(" ", "")).encode("utf-8")`.

Removing the final `.encode("utf-8")` fixes the problem for me. I was surprised by the encode since the other urls aren't encoded at this stage and I would expect `requests` or `urllib` to handle the encoding.

**Comment by jjmaldonis** [comment] 2020-09-08 18:40
Are you sure about this? Cass has been out for 3+ years and we've never had any issues with this before. The utf-8 encoding was explicitly meant to handle non-ascii characters.

**Comment by blimmo** [comment] 2020-09-09 20:15
The code I supplied is a minimal example. At least on my machine (Windows 10, python 3.8) it definitely fails with the error I described.

I agree utf-8 is a great way to handle non-ascii characters but the reason I found it strange here is that `str.encode` returns a `bytes` object. So while the other ways of calling this endpoint produce `str` `url`s, this one produces a `bytes` `url`.

**Comment by shparki** [comment] 2020-10-22 01:41
Is this issue still open? I can submit some work towards this if so.

**Comment by paaksing** [comment] 2020-10-22 01:57
@shparki It is still open for anything weird happening again, you can submit a PR if you like to and link it here.

**Comment by jjmaldonis** [comment] 2020-11-23 23:56
@blimmo @shparki I am not able to reproduce this issue.

The reason the summoner-by-name url is the only query that has `.encode("utf-8")` is because it is the only url that can take non-ascii characters.

My guess is that this error is machine-dependent, and if you can provide more info around that then I'd be happy to fix it. As things stand now, I am hesitant to remove `.encode("utf-8")` because it may break other platforms. If you can find some documentation about urllib or about python in general that indicates that encoding urls with utf-8 is no longer needed, I'll be much more likely to make this change.

Also, if anyone else is seeing this issue, please comment saying so and tell us about your environment (windows? mac? linux? are you using conda? anything else that might be relevant).

**Comment by xSparfuchs** [comment] 2020-12-04 23:01
I have the same problem. My summoner name has a `ú` in it and in the call url it becomes `\xc3\xba` which results in a 403.

Windows
Python 3.6
cassiopeia 4.0.14

**Comment by xSparfuchs** [comment] 2020-12-04 23:32
@blimmo 
A quick fix for that problem would be to correctly escape the summoner name beforehand.
`urllib.parse.quote(summoner_name)`
I don't know how the issue doesn't exist for you @jjmaldonis as `.encode("utf-8")` always results in strings escaped like `ú -> \xc3\xba` which is not the correct way to escape URL's. 
For reference (and possibly a fix): https://stackoverflow.com/questions/40162572/utf-8-encoding-issue-with-python-3

**Comment by paaksing** [comment] 2020-12-05 02:35
@shparki Yep, I use `urllib.parse.quote` to turn characters into percent premised values. `.encode("utf-8")` is something for json files and other things. @jjmaldonis What's your take on this one ?

**Comment by blimmo** [comment] 2020-12-11 16:03
It appears the problem is with calling requests with bytes objects with non-ascii characters.

Internally requests uses urllib to parse urls which attempts to decode the bytes into ascii.

Since I suspect that the inconsistency across platforms is caused by not using requests perhaps these examples will be more reproducable:
- `requests.get("https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/é")` successfully makes the request before failing with a 401 since I haven't specified any authorization details.
- `requests.get("https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/é".encode("utf-8"))` fails with the same error as my original post.

The url produced by [the line](https://github.com/meraki-analytics/cassiopeia/blob/d1a37a9783e4d65a2460fcad742cabd3e03e26d3/cassiopeia/datastores/riotapi/summoner.py#L38) I linked earlier is eventually handed to requests just as in those examples. So if handed bytes (like the return from `.encode("utf-8")`), requests will fail in just the same way.

The [stackoverflow answer](https://stackoverflow.com/questions/40162572/utf-8-encoding-issue-with-python-3) linked above mentions that requests has built in IRI handling so I would expect just handing over the string would be fine (and in my tests is)

Also here's the full traceback from my original MCVE (I've just realized I missed it out back then):

```python
Traceback (most recent call last):
  File ".../test.py", line 8, in <module>
    s.exists
  File "...\lib\site-packages\cassiopeia\core\summoner.py", line 120, in exists
    self.__load__()
  File "...\lib\site-packages\cassiopeia\core\common.py", line 274, in __load__
    self.__load__(group)
  File "...\lib\site-packages\cassiopeia\core\common.py", line 281, in __load__
    data = configuration.settings.pipeline.get(type=self._load_types[load_group], query=query)
  File "...\lib\site-packages\datapipelines\pipelines.py", line 459, in get
    return handler.get(query, context)
  File "...\lib\site-packages\datapipelines\pipelines.py", line 185, in get
    result = self._source.get(self._source_type, deepcopy(query), context)
  File "...\lib\site-packages\datapipelines\sources.py", line 120, in get
    return source.get(type, deepcopy(query), context)
  File "...\lib\site-packages\datapipelines\sources.py", line 69, in wrapper
    return call(self, query, context=context)
  File "...\lib\site-packages\datapipelines\queries.py", line 326, in wrapped
    return method(self, query, context)
  File "...\lib\site-packages\cassiopeia\datastores\riotapi\summoner.py", line 48, in get_summoner
    data = self._get(url, {}, app_limiter=app_limiter, method_limiter=method_limiter)
  File "...\lib\site-packages\cassiopeia\datastores\riotapi\common.py", line 225, in _get
    return request()
  File "...\lib\site-packages\cassiopeia\datastores\riotapi\common.py", line 265, in __call__
    body, response_headers = self.service._client.get(url=self.url,
  File "...\lib\site-packages\cassiopeia\datastores\common.py", line 194, in get
    r = HTTPClient._get(url, headers, rate_limiters)
  File "...\lib\site-packages\cassiopeia\datastores\common.py", line 179, in _get
    r = requests.get(url, headers=request_headers)
  File "...\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "...\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "...\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "...\lib\site-packages\requests\sessions.py", line 446, in prepare_request
    auth = get_netrc_auth(request.url)
  File "...\lib\site-packages\requests\utils.py", line 194, in get_netrc_auth
    ri = urlparse(url)
  File "C:\Program Files\Python38\lib\urllib\parse.py", line 372, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "C:\Program Files\Python38\lib\urllib\parse.py", line 124, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "C:\Program Files\Python38\lib\urllib\parse.py", line 108, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "C:\Program Files\Python38\lib\urllib\parse.py", line 108, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 65: ordinal not in range(128)```

**Comment by jjmaldonis** [comment] 2020-12-12 17:47
Fixed with latest commits

**Closed by jjmaldonis** 2020-12-12 17:47 UTC

**Comment by caffeinism** [comment] 2021-09-25 08:39
This still causes problems with pycurl.
