### ISSUE TITLE
begin_time seems to be ignored during API calls in get_match_history

### ISSUE THREAD

**Issue by InvalidPointer** [meraki-analytics/cassiopeia#192] opened 2018-01-29 11:21 UTC
I set begin_time, but cass makes a bunch of calls like:
`
Making call: https://na1.api.riotgames.com/lol/match/v3/matchlists/by-account/#########?beginIndex=0&endIndex=100
Making call: https://na1.api.riotgames.com/lol/match/v3/matchlists/by-account/#########?beginIndex=100&endIndex=200
Making call: https://na1.api.riotgames.com/lol/match/v3/matchlists/by-account/#########?beginIndex=200&endIndex=300`

And only then it filters needed matches. So there are lots of unnecessary API calls.

**Comment by jjmaldonis** [comment] 2018-01-29 15:21
Did you install Cass from pypi? If so, could you update it by installing from github using this command:  `pip install --upgrade git+https://github.com/meraki-analytics/cassiopeia.git` and try again? Hopefully this problem is fixed in github, and we just need to make a new release.

**Comment by InvalidPointer** [comment] 2018-01-30 11:19
Yup, seems it has been fixed. Thanks!

**Comment by InvalidPointer** [comment] 2018-02-07 13:51
Uh, but I've encountered this again. Seems like parameter begin_time not included in query. In fixed version it wasn't in query either (as much as I remember) but filtering worked.

**Comment by jjmaldonis** [comment] 2018-02-07 16:32
Make sure you are using `cass.get_match_history(...)`.

**Comment by InvalidPointer** [comment] 2018-02-07 16:34
Yes, my call looks like: `mh = cass.get_match_history(s, begin_time=start + shifts[s.region.value])`

**Comment by jjmaldonis** [comment] 2018-02-07 16:35
As far as I know everything is working on my end. Can you post a full code example and explain what is going wrong?

**Comment by InvalidPointer** [comment] 2018-02-08 20:23
This line of code (`cass.get_match_history(s, begin_time=start + shifts[s.region.value])`) produces such output:
Making call: https://na1.api.riotgames.com/lol/match/v3/matchlists/by-account/#########?beginIndex=0&endIndex=100
And so on till something like: https://na1.api.riotgames.com/lol/match/v3/matchlists/by-account/#########?beginIndex=3900&endIndex=4000
Problems:
1. don't use time in API call;
2. goes through all matches which takes too much time;

**Comment by jjmaldonis** [comment] 2018-02-09 21:30
I'm not able to reproduce your issue. It seems to be working for me. Can you test the code below and see if you get the same output (there may be a few extra API calls to get things like champion data)?

I am using the following code:

```
    summoner = Summoner(name="Kalturi", id=21359666, region="NA")
    start = cass.Patch.from_str("8.2", region="NA").start
    print(start)
    mh = cass.get_match_history(summoner=summoner, begin_time=start)
    for m in mh:
        print(m.participants[summoner].champion.name, m.creation)
    print(len(mh))
```

which produces the following output (and it seems correct to me):

```
2018-01-24T03:00:00-08:00
Making call: https://na1.api.riotgames.com/lol/match/v3/matchlists/by-account/34718348?beginIndex=0&endIndex=100
Azir 2018-02-08T03:07:00.250000+00:00
Azir 2018-02-08T02:31:55.113000+00:00
Teemo 2018-02-07T05:08:19.708000+00:00
Taliyah 2018-02-06T03:10:39.395000+00:00
Azir 2018-02-04T07:29:10.886000+00:00
Diana 2018-02-04T06:44:58.865000+00:00
Diana 2018-02-04T06:03:09.479000+00:00
Diana 2018-02-04T05:23:09.757000+00:00
Twitch 2018-02-04T04:47:54.725000+00:00
Diana 2018-02-04T03:57:45.751000+00:00
Diana 2018-02-04T03:14:10.880000+00:00
Xerath 2018-02-04T02:39:55.284000+00:00
Diana 2018-02-04T01:51:16.832000+00:00
Diana 2018-02-04T01:15:45.741000+00:00
Diana 2018-02-04T00:21:54.415000+00:00
Diana 2018-02-03T05:47:29.966000+00:00
Diana 2018-02-03T05:23:27.880000+00:00
Diana 2018-02-03T04:49:21.616000+00:00
Twitch 2018-02-03T04:16:02.838000+00:00
Diana 2018-02-03T03:07:40.899000+00:00
Diana 2018-02-03T02:27:57.589000+00:00
Diana 2018-02-02T22:35:14.845000+00:00
Diana 2018-02-02T02:03:03.339000+00:00
Diana 2018-02-02T01:12:38.135000+00:00
Diana 2018-02-02T00:32:21.338000+00:00
Diana 2018-02-01T23:50:53.849000+00:00
Diana 2018-02-01T02:10:56.943000+00:00
Diana 2018-02-01T01:45:11.771000+00:00
Diana 2018-02-01T00:42:15.133000+00:00
Diana 2018-01-30T22:41:38.383000+00:00
Leona 2018-01-30T22:14:45.981000+00:00
Diana 2018-01-30T21:40:52.643000+00:00
Diana 2018-01-30T21:07:29.640000+00:00
Diana 2018-01-30T20:32:39.236000+00:00
Diana 2018-01-30T02:35:44.581000+00:00
Diana 2018-01-30T01:59:30.289000+00:00
Diana 2018-01-30T01:30:50.764000+00:00
Diana 2018-01-29T02:07:31.523000+00:00
Diana 2018-01-29T01:25:20.189000+00:00
Diana 2018-01-28T06:09:09.717000+00:00
Diana 2018-01-28T05:21:17.108000+00:00
Diana 2018-01-28T04:13:26.061000+00:00
Diana 2018-01-28T03:39:58.116000+00:00
Diana 2018-01-28T03:12:49.163000+00:00
Diana 2018-01-28T02:36:17.308000+00:00
Diana 2018-01-28T02:06:37.159000+00:00
Diana 2018-01-28T00:16:57.833000+00:00
Diana 2018-01-27T23:35:41.172000+00:00
Diana 2018-01-27T23:09:06.370000+00:00
Diana 2018-01-27T22:27:37.614000+00:00
Kled 2018-01-27T03:35:41.803000+00:00
Bard 2018-01-27T03:13:02.817000+00:00
Viktor 2018-01-27T02:48:19.267000+00:00
Diana 2018-01-26T03:32:15.955000+00:00
Diana 2018-01-26T03:00:57.106000+00:00
Diana 2018-01-26T02:35:55.793000+00:00
Diana 2018-01-26T01:56:01.821000+00:00
Diana 2018-01-26T01:13:58.234000+00:00
Diana 2018-01-26T00:32:08.135000+00:00
Diana 2018-01-25T23:38:43.827000+00:00
Diana 2018-01-25T04:45:38.183000+00:00
Diana 2018-01-25T04:12:26.269000+00:00
Diana 2018-01-25T03:36:21.749000+00:00
Diana 2018-01-25T03:01:38.466000+00:00
Diana 2018-01-25T02:25:01.533000+00:00
Diana 2018-01-25T01:45:25.042000+00:00
Diana 2018-01-25T01:08:46.434000+00:00
Diana 2018-01-25T00:16:12.736000+00:00
Diana 2018-01-24T23:52:36.945000+00:00
69
```

**Comment by jjmaldonis** [comment] 2018-02-16 22:19
Since I'm not able to reproduce this I'm going to close it. If you are still having issues feel free to reopen.

**Closed by jjmaldonis** 2018-02-16 22:19 UTC
