### ISSUE TITLE
Summoner spells are broken

### ISSUE THREAD

**Issue by NiliusJulius** [meraki-analytics/cassiopeia#166] opened 2017-11-21 10:56 UTC
The latest commits broke the summoner spells. 
The following error is given:
'SummonerSpellData' object has no attribute 'includedData'

**Comment by jjmaldonis** [comment] 2017-11-21 18:33
Ok thanks. Can you please post your code and the full error message (it will be large)? I can't reproduce the error using my tests. I'm sure there are a few other bugs like this in the last commit, but hopefully not too many.

**Comment by NiliusJulius** [comment] 2017-11-21 19:15
name = request.GET['name']
summ = Summoner(name=name)
current_match = summ.current_match
print(current_match.participants[0].summoner_spell_d.image.url)

`Traceback:

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\merakicommons\cache.py" in wrapper
  16.             return values[self]

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\weakref.py" in __getitem__
  365.         return self.data[ref(key)]

During handling of the above exception (<weakref at 0x0574A360; to 'SummonerSpell' at 0x05747790>), another exception occurred:

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\merakicommons\ghost.py" in wrapper
  41.                 return method(*args, **kwargs)

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\merakicommons\cache.py" in wrapper
  18.             values[self] = method(self)

File "C:\Users\Niels\Websites\cassiopeia\cassiopeia\core\staticdata\summonerspell.py" in image
  290.         image = Image.from_data(self._data[SummonerSpellData].image)

During handling of the above exception ('SummonerSpellData' object has no attribute 'image'), another exception occurred:

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\merakicommons\ghost.py" in __get__
  87.                 return self.fget(obj)

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\merakicommons\ghost.py" in wrapper
  43.                 raise GhostLoadingRequiredError(str(error))

During handling of the above exception ('SummonerSpellData' object has no attribute 'image'), another exception occurred:

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py" in inner
  41.             response = get_response(request)

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\Niels\Websites\lol\lolweb\views.py" in summoner
  43.     print(current_match.participants[0].summoner_spell_d.image.url)

File "C:\Users\Niels\AppData\Local\Programs\Python\Python36-32\lib\site-packages\merakicommons\ghost.py" in __get__
  90.                 obj.__load__(load_group)

File "C:\Users\Niels\Websites\cassiopeia\cassiopeia\core\common.py" in __load__
  228.             query = self.__get_query__()

File "C:\Users\Niels\Websites\cassiopeia\cassiopeia\core\staticdata\summonerspell.py" in __get_query__
  142.         query = {"region": self.region, "platform": self.platform, "version": self.version, "locale": self.locale, "includedData": self.included_data}

File "C:\Users\Niels\Websites\cassiopeia\cassiopeia\core\staticdata\summonerspell.py" in included_data
  177.         return self._data[SummonerSpellData].includedData

Exception Type: AttributeError at /summoner/
Exception Value: 'SummonerSpellData' object has no attribute 'includedData'
`

**Comment by jjmaldonis** [comment] 2017-11-21 19:22
Thanks that was really helpful information. It should be fixed now if you re-pull.

**Closed** 2017-11-21 19:22 UTC

**Comment by NiliusJulius** [comment] 2017-11-21 19:24
It works. thanks!
